/**
 * Math is Punk — Phase Notes
 *
 * Phase 0 — Naming & Setup ✅
 * - Basic landing page live on Cloudflare Pages.
 * - Tech stack: Next.js (App Router, TypeScript, Tailwind), dark theme, minimal UI.
 *
 * Phase 1 — The Playground v1 🧪 ✅
 * - /playground layout with controls + canvas.
 * - First visual experiment with live-tweak controls.
 * - Refactored into reusable components for future experiments.
 *
 * Phase 2 — Today in Mathematics 🧮✨ ✅
 * - Daily deterministic art served from S3 (Lambda + EventBridge).
 * - /today page shows the daily drop; /today/archive placeholder ready.
 *
 * Phase 3 — Generators Lab (in progress)
 * - Expand beyond daily drops into fractals, prime spirals, chaos attractors, and more.
 */
export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center bg-black text-white px-4">
      <div className="max-w-2xl text-center space-y-6">
        <h1 className="text-4xl md:text-6xl font-bold tracking-tight">
          Math is <span className="underline decoration-pink-500">Punk</span>.
        </h1>

        <p className="text-lg md:text-2xl text-gray-300">
          A pointless, over-engineered math-art playground with a daily drop.
        </p>

        <p className="text-sm md:text-base text-gray-400">
          Coming soon: chaotic attractors, prime spirals, useless calculators, 
          and absurd proofs. No test prep. No formulas to memorise. Just vibes.
        </p>

        <div className="text-left text-sm text-gray-400 space-y-2 max-w-xl mx-auto">
          <div className="flex flex-col gap-1 border border-gray-800 rounded-lg px-4 py-3 bg-gray-900/60">
            <div className="flex items-center justify-between">
              <span className="text-gray-200">Phase 0 · Naming & Setup</span>
              <span className="text-green-400 uppercase tracking-[0.1em] text-xs">Complete</span>
            </div>
            <p className="text-gray-500">
              Live landing page, dark theme, and deployment wired to Cloudflare Pages.
            </p>
          </div>
          <div className="flex flex-col gap-1 border border-gray-800 rounded-lg px-4 py-3 bg-gray-900/60">
            <div className="flex items-center justify-between">
              <span className="text-gray-200">Phase 1 · Playground v1</span>
              <span className="text-green-400 uppercase tracking-[0.1em] text-xs">Complete</span>
            </div>
            <p className="text-gray-500">
              Two-column lab layout with the first experiment and live-tweak controls.
            </p>
          </div>
          <div className="flex flex-col gap-1 border border-gray-800 rounded-lg px-4 py-3 bg-gray-900/60">
            <div className="flex items-center justify-between">
              <span className="text-gray-200">Phase 2 · Today in Mathematics</span>
              <span className="text-green-400 uppercase tracking-[0.1em] text-xs">Complete</span>
            </div>
            <p className="text-gray-500">
              Deterministic daily art generated by Lambda + S3 and surfaced on /today with an archive stub.
            </p>
          </div>
          <div className="flex flex-col gap-1 border border-pink-700/60 rounded-lg px-4 py-3 bg-pink-950/30">
            <div className="flex items-center justify-between">
              <span className="text-gray-200">Phase 3 · Generators Lab</span>
              <span className="text-pink-300 uppercase tracking-[0.1em] text-xs">In progress</span>
            </div>
            <p className="text-gray-500">
              Expand into fractals, prime spirals, chaos attractors, golden-ratio fields, and modular lattices—an extensible lab for evolving generators and their histories.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
