AWSTemplateFormatVersion: '2010-09-09' # SAM template defining the backend Lambda, S3 storage, API, and daily schedule
Transform: AWS::Serverless-2016-10-31
Description: Math is Punk backend (daily art Lambda)

Resources:
  GenerateDailyArtFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Handler: handler.generate_daily_art
      CodeUri: ../backend/daily_art_lambda
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          DAILY_ART_BUCKET: !Ref DailyArtBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref DailyArtBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /daily-art/generate
            Method: get
        DailySchedule:
          Type: Schedule
          Properties:
            # Run shortly after midnight UTC so the day's art exists when users first visit.
            Schedule: cron(5 0 * * ? *)

  DailyArtBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "math-is-punk-daily-art-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  DailyArtBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DailyArtBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${DailyArtBucket.Arn}/*"

Outputs:
  GenerateDailyArtApiUrl:
    Description: API Gateway URL for GenerateDailyArtFunction (Prod)
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/daily-art/generate"
  DailyArtBucketName:
    Description: S3 bucket that stores daily art SVGs
    Value: !Ref DailyArtBucket
